---

- name: filen | Install filen desktop client (ubuntu)
  when: is_ubuntu
  become: true
  become_user: "{{ user_username }}"
  block:
    - name: filen | Download filen app
      ansible.builtin.get_url:
        dest: "{{ ansibleTmp }}/filen.deb"
        mode: "0644"
        url: "{{ filen.deb }}/filen.rpm"

    - name: filen | Install desktop app
      ansible.builtin.apt:
        deb: "{{ ansibleTmp }}/filen.deb"
        state: present

- name: filen | Install filen desktop client (fedora)
  when: is_fedora
  become: true
  become_user: "{{ user_username }}"
  block:
    - name: filen | Download filen app
      ansible.builtin.get_url:
        dest: "{{ ansibleTmp }}/filen.rpm"
        mode: "0644"
        url: "{{ filen.rpm }}"

    - name: filen | Install desktop app
      ansible.builtin.dnf:
        name: "{{ ansibleTmp }}/filen.rpm"
        state: present
