---

- name: Create tmp folder
  become: true
  become_user: "{{ user_username }}"
  ansible.builtin.file:
    group: "{{ user_username }}"
    mode: "0754"
    path: "/tmp/anisible_tmp_{{ user_username }}"
    state: directory

- name: Set tmp folder fact
  ansible.builtin.set_fact:
    tmp_dir: "/tmp/anisible_tmp_{{ user_username }}"

- name: filen | Install filen desktop client (ubuntu)
  when: is_ubuntu
  block:
    - name: filen | Download filen app
      become: true
      become_user: "{{ user_username }}"
      ansible.builtin.get_url:
        dest: "{{ tmp_dir }}/filen.deb"
        mode: "0644"
        url: "{{ filen.deb }}/filen.rpm"

    - name: filen | Install desktop app
      become: true
      ansible.builtin.apt:
        deb: "{{ tmp_dir }}/filen.deb"
        state: present

- name: filen | Install filen desktop client (fedora)
  when: is_fedora
  block:
    - name: filen | Download filen app
      become: true
      become_user: "{{ user_username }}"
      ansible.builtin.get_url:
        dest: "{{ tmp_dir }}/filen.rpm"
        mode: "0644"
        url: "{{ filen.rpm }}"

    - name: filen | Install desktop app
      become: true
      ansible.builtin.dnf:
        disable_gpg_check: true
        name: "{{ tmp_dir }}/filen.rpm"
        state: present
