---

- name: pip | Install pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: pip | Install gnome extensions cli
  become: true
  become_user: "{{ user_username }}"
  ansible.builtin.pip:
    name: gnome-extensions-cli
    extra_args: --user --upgrade
