---

- name: Debug vars
  ansible.builtin.debug:
    msg:
      - "apps: {{ apps }}"
      - "group_name: {{ group_name }}"
      - "remote: {{ remote }}"

- name: "flatpak | Install {{ group_name }}"
  community.general.flatpak:
    method: user
    name: "{{ app_name }}"
    remote: "{{ remote }}"
    state: present
  loop: "{{ apps }}"
  loop_control:
    loop_var: app_name