---

- name: flatpak | Add flathub to flatpak remotes for user
  become: true
  become_user: "{{ user_username }}"
  community.general.flatpak_remote:
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
    name: flathub
    state: present

# These will be replaced with flatpak versions
- name: flatpak | Remove non-flatpak gnome apps
  become: true
  ansible.builtin.package:
    name: "{{ app_name }}"
    state: absent
  loop: "{{ gnome.remove.core }}"
  loop_control:
    loop_var: app_name

- name: flatpak | Install GNOME Software Flatpak plugin
  when: is_ubuntu
  become: true
  ansible.builtin.package:
    name: gnome-software-plugin-flatpak
    state: present

- name: flatpak | Install flatseal
  become: true
  become_user: "{{ user_username }}"
  community.general.flatpak:
    method: user
    name: com.github.tchx84.Flatseal
    state: present
