---

- name: nautilus | Changes that take effect immediately
  when: is_gnome
  become: true
  become_user: "{{ user_username }}"
  block:
    - name: nautilus | Dirs sorted with files
      community.general.dconf:
        key: /org/gtk/gtk4/settings/file-chooser/sort-directories-first
        state: present
        value: "false"

    - name: nautilus | Hide hidden files
      community.general.dconf:
        key: /org/gtk/gtk4/settings/file-chooser/show-hidden
        state: present
        value: "false"

    - name: nautilus | Set single-click to open
      community.general.dconf:
        key: /org/gnome/nautilus/preferences/click-policy
        state: present
        value: "'single'"

    - name: nautilus | Show create link
      community.general.dconf:
        key: /org/gnome/nautilus/preferences/show-create-link
        state: present
        value: "true"

- name: nautilus | Changes that take effect when nautilus is restarted
  when: is_gnome
  become: true
  become_user: "{{ user_username }}"
  block:
    - name: nautilus | Maximise window
      become: true
      become_user: "{{ user_username }}"
      community.general.dconf:
        key: /org/gnome/nautilus/window-state/maximized
        state: present
        value: "true"

    - name: nautilus | Set icon view
      become: true
      become_user: "{{ user_username }}"
      community.general.dconf:
        key: /org/gnome/nautilus/preferences/default-folder-viewer
        state: present
        value: "'icon-view'"

- name: nautilus | Add epub thumbnail support to nautilus
  become: true
  become_user: "{{ user_username }}"
  ansible.builtin.package:
    name: gnome-epub-thumbnailer
    state: present
