---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

# - name: Add/remove gnome extension
#   ansible.builtin.import_tasks:
#     file: ./gnome/extensions.yaml

- name: extensions_add | Install TEST"
  jaybeede.linux_desktop.gnome_extensions:
    action: enable
    url: https://github.com/stuarthayhurst/alphabetical-grid-extension
