---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Create tmp folder
  become: true
  become_user: "{{ user_username }}"
  ansible.builtin.file:
    group: "{{ user_username }}"
    mode: "0754"
    path: "/tmp/anisible_tmp_{{ user_username }}"
    state: directory

- name: Set tmp folder fact
  ansible.builtin.set_fact:
    tmp_dir: "/tmp/anisible_tmp_{{ user_username }}"

- name: packages | Install python3-psutil
  ansible.builtin.package:
    name: python3-psutil
    state: present

- name: Add/remove gnome extensions
  become: true
  become_user: "{{ user_username }}"
  block:
    - name: extensions | Add user extensions
      ansible.builtin.include_tasks: ./gnome/extensions_add.yaml
      vars:
        exts: "{{ gnome.add.user }}"
        group_name: user

- name: extensions_install | Set dconf disabled extensions
  community.general.dconf:
    key: /org/gnome/shell/disabled-extensions
    state: present
    value: []

- name: extensions_install | Set dconf enabled extensions
  community.general.dconf:
    key: /org/gnome/shell/enabled-extensions
    state: present
    value: []
