---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Create tmp folder
  become: true
  ansible.builtin.file:
    path: "/tmp/anisible_tmp_{{ user_username }}"
    state: directory
    mode: 0644

- name: Set tmp folder fact
  ansible.builtin.set_fact:
    tmp_dir: "/tmp/anisible_tmp_{{ user_username }}"

- name: Debug extension facts
  ansible.builtin.debug:
    msg:
      - "tmp_dir: {{ tmp_dir }}"

- name: Add/remove gnome extension
  ansible.builtin.import_tasks:
    file: ./gnome/extensions.yaml
