---

- name: settings_update | Create settings folder for ({{ app | basename }})
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.file:
    path: "/home/{{ user.username }}/.var/app/{{ app | basename }}/config/glib-2.0/settings"
    state: directory
    mode: '0700'

- name: settings_update | Updating settings for ({{ app | basename }})
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    dest: "/home/{{ user.username }}/.var/app/{{ app | basename }}/config/glib-2.0/settings/keyfile"
    group: "{{ user.username }}"
    mode: preserve
    owner: "{{ user.username }}"
    src: "{{ app }}"
