---

- name: settings_update | Create settings file for {{ app | basename }}
  become: true
  become_user: "{{ user_username }}"
  ansible.builtin.copy:
    dest: "/home/{{ user_username }}/.var/app/{{ app | basename }}/config/glib-2.0/settings/keyfile"
    group: "{{ user_username }}"
    mode: preserve
    owner: "{{ user_username }}"
    src: "{{ app | basename }}"
