---

- name: ibmplex | Install font
  ansible.builtin.package:
    name: "{{ font_ibmplex }}"
    state: present


- name: ibmplex | Remove unrequired languages
  ansible.builtin.file:
    path: "/usr/share/fonts/{{ item }}"
    state: absent
  with_items:
    - ibm-plex-sans-arabic-fonts
    - ibm-plex-sans-devanagari-fonts
    - ibm-plex-sans-hebrew-fonts
    - ibm-plex-sans-thai-fonts
    - ibm-plex-sans-thai-looped-fonts