---

- name: mscorefonts | Install font
  when: is_fedora
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
    state: present


- name: mscorefonts | Install font
  when: is_ubuntu
  block:
    - name: mscorefonts | Accept eula
      ansible.builtin.debconf:
        name: "{{ font_mscore }}"
        question: "msttcorefonts/accepted-mscorefonts-eula"
        value: "true"
        vtype: "select"

    - name: mscorefonts | Install fonts
      ansible.builtin.apt:
        name: "{{ font_mscore }}"
        state: present

