---

- name: sourcecodepro | Install font
  when: is_fedora
  ansible.builtin.package:
    name: adobe-source-code-pro-fonts
    state: present

- name: sourcecodepro | Install font
  when: is_ubuntu
  block:
    - name: sourcecodepro | Download archive
      ansible.builtin.get_url:
        dest: "{{ ansibleTmp }}/scp.zip"
        mode: "0600"
        url: "https://github.com/adobe-fonts/source-code-pro/releases/download/2.042R-u%2F1.062R-i%2F1.026R-vf/TTF-source-code-pro-2.042R-u_1.062R-i.zip"

    - name: sourcecodepro | Create tmp folder
      ansible.builtin.file:
        mode: "0600"
        path: "{{ ansibleTmp }}/scp/"
        state: directory

    - name: sourcecodepro | Extact to tmp folder
      ansible.builtin.unarchive:
        copy: false
        dest: "{{ ansibleTmp }}/scp/"
        src: "{{ ansibleTmp }}/scp.zip"

    - name: sourcecodepro | Copy to font folder
      ansible.builtin.copy:
        dest: "/usr/share/fonts/SourceCodePro"
        mode: "0600"
        src: "{{ ansibleTmp }}/scp/OTF"
