---

- name: ubuntu | Check if font already installed
  ansible.builtin.stat:
    path: "/usr/share/fonts/ubuntu-family/Ubuntu-B.ttf"
  register: ubuntu_fonts_installed

- name: ubuntu | Not installing
  when: ubuntu_fonts_installed
  ansible.builtin.debug:
    msg: ubuntu fonts are already installed
  
- name: ubuntu | Install font
  when: is_fedora and not ubuntu_fonts_installed
  block:
    - name: ubuntu | Add ubuntu font support
      ansible.builtin.command:
        cmd: "sudo dnf copr enable atim/ubuntu-fonts -y"

    - name: ubuntu | Install font
      ansible.builtin.package:
        name: ubuntu-family-fonts
        state: present
