---

# validate_certs=False as extensions.gnome.org often has cert issues.
- name: extensions_install2 | Get extension info
  ansible.builtin.set_fact:
    ext_info: "{{ lookup('url', 'https://extensions.gnome.org/extension-info/?uuid=' ~ ext.uuid ~ '&shell_version=' ~ desktop_version,validate_certs=False) }}"

- name: extensions_install2 | Get download url
  ansible.builtin.set_fact:
    ext_download_url: "{{ (ext_info | from_json).download_url }}"

- name: extensions_install2 | Debug exxt url
  ansible.builtin.debug:
    msg:
      - "ext_info: {{ ext_info }}"
      - "ext_download_url: {{ ext_download_url }}"
      - "ext: {{ ext }}"
      - "tmp_dir: {{ tmp_dir }}"

- name: extensions_install2 | Create download folder
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ ext.uuid }}/"
    state: directory
    mode: "0644"

# validate_certs=False as extensions.gnome.org often has cert issues.
- name: extensions_install2 | Download ext
  ansible.builtin.get_url:
    dest: "{{ tmp_dir }}/{{ ext.uuid }}/{{ ext.uuid }}.zip"
    mode: "0644"
    url: "https://extensions.gnome.org{{ ext_download_url }}"
    validate_certs: false
