---

- name: extensions_add | Check if is already installed {{ ext.uuid }}
  ansible.builtin.stat:
    path: /home/{{ profileUsername }}/.local/share/gnome-shell/extensions/{{ extUuid }}
  register: gnome_extension_check

- name: extensions_add | {{ extension.name }}
  when: not gnome_extension_check.stat.exists
  block:
    - name: extensions_add | Download
      ansible.builtin.get_url:
        dest: "/tmp/gnomeExtensions/{{ ext.uuid }}.zip"
        mode: "0600"
        url: "https://extensions.gnome.org/extension-data/{{ extension.url }}"

    # enable command does not work, so manual enabling is still required
    - name: extensions_add | Install
      ansible.builtin.command:
        cmd: gnome-extensions install "/tmp/gnomeExtensions/{{ ext.uuid }}.zip"
      #changed_when: my_output.rc != 0 
