---

- name: extensions | Add gnome user extensions
  become: true
  become_user: "{{ user_username }}"
  block:
    - name: extensions | Add user extensions
      ansible.builtin.include_tasks: ./extensions_add.yaml
      vars:
        exts: "{{ gnome.add.user }}"
        group_name: user
