---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Configure gnome
  when: is_gnome
  loop_control:
    loop_var: file
  ansible.builtin.include_tasks: "{{ file }}"
  with_fileglob:
    - ./settings/*.yaml
