---

font_droid_mono: google-droid-sans-mono-fonts
font_fira_code: fonts-firacode
font_ibmplex: fonts-ibm-plex
font_inconsolata: fonts-inconsolata
font_mscore: ttf-mscorefonts-installer

gnome_extensions:
  - name: "alphabetical-app-grid"
    url: "AlphabeticalAppGridstuarthayhurst.v40.shell-extension.zip"
    uuid: "AlphabeticalAppGrid@stuarthayhurst"

  - name: "color-picker"
    url: "color-pickertuberry.v44.shell-extension.zip"
    uuid: "color-picker@tuberry"
