---

user_username: stephen

# Gnome extensions to add/remove
gnome2:
  add:
    system:
      - https://github.com/stuarthayhurst/alphabetical-grid-extension
      - https://gitlab.com/knokelmaat/display-configuration-switcher-gnome-extension

    user:
      - https://github.com/tuberry/color-picker

  remove:
    system:
      - apps-menu@gnome-shell-extensions.gcampax.github.com
      - launch-new-instance@gnome-shell-extensions.gcampax.github.com
      - places-menu@gnome-shell-extensions.gcampax.github.com
      - window-list@gnome-shell-extensions.gcampax.github.com
      - ding@rastersoft.com
      - tiling-assistant@ubuntu.com

gnome:
  add:
    system:
      - url: "AlphabeticalAppGridstuarthayhurst.v40.shell-extension.zip"
        uuid: "AlphabeticalAppGrid@stuarthayhurst"
    user:
      - url: "color-pickertuberry.v44.shell-extension.zip"
        uuid: "color-picker@tuberry"
