---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Setup flatpak
  ansible.builtin.import_tasks:
    file: ./flatpak/flatpak.yaml

- name: Install software from flathub
  ansible.builtin.import_tasks:
    file: ./flatpak/flathub.yaml
