---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Setup flatpak
  ansible.builtin.import_tasks:
    file: ./flatpak/flatpak.yaml

- name: Install software from flathub
  ansible.builtin.import_tasks:
    file: ./remotes/flathub.yaml

- name: Install software with multiple steps
  ansible.builtin.include_tasks: "{{ app_file }}"
  with_fileglob:
    - ./software/*.yaml
  loop_control:
    loop_var: app_file
