---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Setup flatpak
  ansible.builtin.import_tasks:
    file: ./flatpak/flatpak.yaml

- name: Install audio software
  become: true
  become_user: "{{ user_username }}"
  community.general.flatpak:
    name: "{{ app_name }}"
    state: present
    method: user
  loop: "{{ flathub.audio }}"
  loop_control:
    loop_var: app_name

- name: Install browsers
  become: true
  become_user: "{{ user_username }}"
  community.general.flatpak:
    name: "{{ app_name }}"
    state: present
    method: user
  loop: "{{ flathub.browsers }}"
  loop_control:
    loop_var: app_name

- name: Install development tools
  become: true
  become_user: "{{ user_username }}"
  community.general.flatpak:
    name: "{{ app_name }}"
    state: present
    method: user
  loop: "{{ flathub.development }}"
  loop_control:
    loop_var: app_name

- name: Install gnome circle apps
  become: true
  become_user: "{{ user_username }}"
  community.general.flatpak:
    name: "{{ app_name }}"
    state: present
    method: user
  loop: "{{ flathub.gnome_circle }}"
  loop_control:
    loop_var: app_name
