---

- name: packages | Add/remove packages
  become: true
  block:
    # These will be replaced with flatpak versions
    - name: packages | Uninstall gnome
      when: is_gnome
      ansible.builtin.import_tasks: ./packages_remove.yaml
      vars:
        apps: "{{ packages.remove.gnome }}"
        group_name: gnome

    - name: packages | Uninstall productivity
      ansible.builtin.import_tasks: ./packages_remove.yaml
      vars:
        apps: "{{ packages.remove.productivity }}"
        group_name: productivity

    - name: packages | Install gnome
      when: is_gnome
      ansible.builtin.import_tasks: ./packages_add.yaml
      vars:
        apps: "{{ packages.add.gnome }}"
        group_name: gnome

    - name: packages | Install python3-psutil
      ansible.builtin.package:
        name: python3-psutil
        state: present
