---

- name: Include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: Get facts
  ansible.builtin.package_facts:
    manager: auto

- name: Get desktop environment
  ansible.builtin.command:
    cmd: echo $XDG_CURRENT_DESKTOP
  register: xdg_desktop
  changed_when: false
  environment:
    XDG_CURRENT_DESKTOP: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"

- name: Set facts
  ansible.builtin.set_fact:
    desktop: "{{ xdg_desktop | lower }}"
    distro: "{{ ansible_distribution | lower }}"
    distro_version: "{{ ansible_distribution_major_version }}"
    is_fedora: '{{ ((ansible_distribution | lower) == "fedora") | ternary(true, false) }}'
    is_ubuntu: '{{ ((ansible_distribution | lower) == "ubuntu") | ternary(true, false) }}'
    is_virtual: '{{ (ansible_virtualization_role == "guest") | ternary(true, false) }}'

- name: Debug facts
  when: debug_vars
  ansible.builtin.debug:
    msg:
      - "desktop: {{ desktop }}"
      - "distro: {{ distro }}"
      - "distro_version: {{ distro_version }}"
      - "is_fedora: {{ is_fedora }}"
      - "is_ubuntu: {{ is_ubuntu }}"
      - "is_virtual: {{ is_virtual }}"

- name: Debug env vars
  when: debug_vars
  ansible.builtin.debug:
    var: ansible_env

- name: Include fedora vars
  when: is_fedora
  ansible.builtin.include_vars:
    file: "fedora.yaml"

- name: Include ubuntu vars
  when: is_ubuntu
  ansible.builtin.include_vars:
    file: "ubuntu.yaml"
