---

- name: include task vars
  ansible.builtin.include_vars:
    file: "task.yaml"

- name: get facts
  ansible.builtin.package_facts:
    manager: auto

- name: set facts
  ansible.builtin.set_fact:
    distro: "{{ ansible_distribution | lower }}"
    distro_version: "{{ ansible_distribution_major_version }}"
    is_fedora: '{{ ((ansible_distribution | lower) == "fedora") | ternary(true, false) }}'
    is_ubuntu: '{{ ((ansible_distribution | lower) == "ubuntu") | ternary(true, false) }}'
    is_virtual: '{{ ansible_virtualization_role == "guest" | ternary(true, false) }}'

- name: debug facts
  ansible.builtin.debug:
    msg:
      - "distro: {{ distro }}"
      - "distro_version: {{ distro_version }}"
      - "is_fedora: {{ is_fedora }}"
      - "is_ubuntu: {{ is_ubuntu }}"
      - "is_virtual: {{ is_virtual }}"
  when: debugVars

- name: include vars for fedora
  ansible.builtin.include_vars:
    file: "fedora.yaml"
  when: is_fedora

- name: include vars for ubuntu
  ansible.builtin.include_vars:
    file: "ubuntu.yaml"
  when: is_ubuntu
    