---

- name: Gather facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set facts
  set_fact:
    distro: "{{ ansible_distribution | lower }}"
    distroVersion: "{{ ansible_distribution_major_version }}"
    isFedora: '{{ ansible_distribution | lower == "fedora" | ternary (true, false) }}'
    isUbuntu: '{{ ansible_distribution | lower == "ubuntu" | ternary (true, false) }}'
    isVirtual: '{{ ansible_virtualization_role == "guest" | ternary (true, false) }}'

- name: Debug facts
  ansible.builtin.debug:
    msg:
      - "distro: {{ distro }}"
      - "distroVersion: {{ distroVersion }}"
      - "isFedora: {{ isFedora }}"
      - "isUbuntu: {{ isUbuntu }}"
      - "isVirtual: {{ isVirtual }}"

- name: Print all gathered facts
  debug:
    var: ansible_facts