---

- name: obs | Copy profiles
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    dest: "/home/stephen/.var/app/com.obsproject.Studio/config/obs-studio/basic"
    group: "{{ user.username }}"
    mode: preserve
    owner: "{{ user.username }}"
    src: "app_config/obs/profiles"

- name: obs | Copy scenes
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    dest: "/home/stephen/.var/app/com.obsproject.Studio/config/obs-studio/basic"
    group: "{{ user.username }}"
    mode: preserve
    owner: "{{ user.username }}"
    src: "app_config/obs/scenes"

- name: obs | Copy settings
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    dest: "/home/stephen/.var/app/com.obsproject.Studio/config/obs-studio"
    group: "{{ user.username }}"
    mode: preserve
    owner: "{{ user.username }}"
    src: "app_config/obs/settings/"
