---

- name: Run base playbook
  ansible.builtin.import_playbook: base.yaml

- name: Run packages playbook
  ansible.builtin.import_playbook: packages.yaml

- name: Run flatpaks playbook
  ansible.builtin.import_playbook: flatpaks.yaml

# - name: Run fonts playbook
#   ansible.builtin.import_playbook: fonts.yaml

# - name: Run filemanagers playbook
#   ansible.builtin.import_playbook: filemanagers.yaml

# - name: Run extensions playbook
#   ansible.builtin.import_playbook: extensions.yaml

# - name: Run extensions terminals
#   ansible.builtin.import_playbook: terminals.yaml

# - name: Run desktop playbook
#   ansible.builtin.import_playbook: desktop.yaml
