---

- name: flathub | Install flatpak apps
  become: true
  become_user: "{{ user_username }}"
  block:
  - name: flathub | Install audio
    ansible.builtin.import_tasks: ../flatpak/add.yaml
    vars:
      apps: "{{ flathub.add.audio }}"
      group_name: audio
      remote: flathub
  
  - name: flathub | Install browsers
    ansible.builtin.import_tasks: ../flatpak/add.yaml
    vars:
      apps: "{{ flathub.add.browsers }}"
      group_name: browsers
      remote: flathub